[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson
    tzapu/WiFiManager
    links2004/WebSockets
    adafruit/Adafruit NeoPixel
    DFRobot/DFRobotDFPlayerMini
    madhephaestus/ESP32Servo